import type { Profile, Campaign, Application } from "@/lib/types/database";

// ---------------------------------------------------------------------------
// Date helper: generates ISO date strings relative to "today" so demo data
// always feels current regardless of when the app is opened.
// ---------------------------------------------------------------------------
function daysFromNow(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  d.setHours(0, 0, 0, 0);
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// Demo advertiser profile
// ---------------------------------------------------------------------------
export const DEMO_ADVERTISER: Profile = {
  id: "demo-advertiser-001",
  role: "advertiser" as const,
  display_name: "박준영",
  email: "demo@adlumin.co.kr",
  phone: "02-6012-3456",
  avatar_url: null,
  is_active: true,
  created_at: daysFromNow(-90),
  updated_at: daysFromNow(-1),
};

export const DEMO_ADVERTISER_PROFILE = {
  id: "demo-advertiser-001",
  company_name: "(주)브라이트커머스",
  business_number: "214-87-45231",
  representative: "박준영",
  business_type: "전자상거래",
  company_address: "서울특별시 강남구 테헤란로 152, 8층",
  company_phone: "02-6012-3456",
  company_website: "https://brightcommerce.co.kr",
  company_logo_url: null,
  company_description:
    "뷰티, IT, 라이프스타일 분야의 D2C 브랜드를 운영하며 연간 200건 이상의 인플루언서 마케팅 캠페인을 집행하고 있습니다.",
  verified: true,
  created_at: daysFromNow(-90),
};

// ---------------------------------------------------------------------------
// Demo influencer profile
// ---------------------------------------------------------------------------
export const DEMO_INFLUENCER: Profile = {
  id: "demo-influencer-001",
  role: "influencer" as const,
  display_name: "라이프로그 서영",
  email: "demo-inf@adlumin.co.kr",
  phone: "010-9876-5432",
  avatar_url: null,
  is_active: true,
  created_at: daysFromNow(-60),
  updated_at: daysFromNow(-1),
};

// ---------------------------------------------------------------------------
// 10 Demo campaigns
// ---------------------------------------------------------------------------
const advertiserTag = {
  company_name: "(주)브라이트커머스",
  id: "demo-advertiser-001",
} as Campaign["advertiser"];

export const DEMO_CAMPAIGNS: Campaign[] = [
  // ── 1. 삼성 갤럭시 버즈3 구매평 체험단 (active, seller, purchase_review) ──
  {
    id: "demo-camp-001",
    advertiser_id: "demo-advertiser-001",
    title: "삼성 갤럭시 버즈3 구매평 체험단",
    description:
      "삼성 갤럭시 버즈3 프로를 직접 구매 후 네이버 스마트스토어에 상세 구매평을 남겨주세요. 음질, 노이즈캔슬링, 착용감 등 실사용 경험을 솔직하게 작성해주시면 됩니다.",
    campaign_type: "seller",
    required_channel: "purchase_review",
    category_name: "IT",
    region: null,
    compensation_type: "product",
    compensation_value: "삼성 갤럭시 버즈3 프로 1개 (259,000원 상당)",
    cash_amount: 0,
    product_name: "삼성 갤럭시 버즈3 프로",
    product_value: 259000,
    purchase_link: "https://smartstore.naver.com/samsung-official",
    purchase_price: 259000,
    max_applicants: 15,
    current_applicants: 12,
    apply_start: daysFromNow(-3),
    apply_end: daysFromNow(11),
    announce_date: daysFromNow(13),
    register_start: daysFromNow(13),
    register_end: daysFromNow(23),
    deadline_date: daysFromNow(25),
    recruitment_start: daysFromNow(-3),
    recruitment_end: daysFromNow(11),
    selection_date: daysFromNow(13),
    content_deadline: daysFromNow(23),
    publish_deadline: daysFromNow(25),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "active",
    is_featured: true,
    is_premium: false,
    view_count: 487,
    provided_items:
      "삼성 갤럭시 버즈3 프로 1개 (색상: 실버 또는 그라파이트 선택 가능)\n충전 케이스 포함",
    search_keywords_text:
      "갤럭시버즈3, 갤럭시버즈3프로, 삼성이어폰, 무선이어폰추천, 노이즈캔슬링이어폰",
    mission:
      "1. 제품 수령 후 개봉기 사진 3장 이상 촬영\n2. 최소 5일 이상 실사용 후 솔직한 구매평 작성\n3. 음질, ANC, 착용감, 배터리 항목별 평가 포함\n4. 필수 키워드 2개 이상 자연스럽게 포함\n5. 별점 솔직하게 반영 (강제 5점 아님)",
    required_qa:
      "Q1. 현재 사용 중인 이어폰 브랜드와 모델명은?\nQ2. 하루 평균 이어폰 사용 시간은?\nQ3. 주로 어떤 환경에서 이어폰을 사용하시나요? (출퇴근, 운동, 사무실 등)",
    guidelines: null,
    required_keywords: ["갤럭시버즈3프로", "무선이어폰추천"],
    required_images_count: 5,
    min_text_length: 500,
    created_at: daysFromNow(-5),
    updated_at: daysFromNow(-3),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 2. 성수동 카페 블로그 체험단 (active, place, blog) ──
  {
    id: "demo-camp-002",
    advertiser_id: "demo-advertiser-001",
    title: "성수동 카페 블로그 체험단",
    description:
      "성수역 3번 출구 도보 5분 거리에 새로 오픈한 스페셜티 카페 '언더독 로스터스'를 방문하고 네이버 블로그 리뷰를 작성해주세요.",
    campaign_type: "place",
    required_channel: "blog",
    category_name: "맛집",
    region: "서울",
    compensation_type: "product",
    compensation_value: "2인 음료 + 디저트 세트 무료 제공 (35,000원 상당)",
    cash_amount: 0,
    product_name: "음료+디저트 세트",
    product_value: 35000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 10,
    current_applicants: 7,
    apply_start: daysFromNow(-5),
    apply_end: daysFromNow(9),
    announce_date: daysFromNow(11),
    register_start: daysFromNow(11),
    register_end: daysFromNow(25),
    deadline_date: daysFromNow(27),
    recruitment_start: daysFromNow(-5),
    recruitment_end: daysFromNow(9),
    selection_date: daysFromNow(11),
    content_deadline: daysFromNow(25),
    publish_deadline: daysFromNow(27),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "active",
    is_featured: true,
    is_premium: false,
    view_count: 324,
    provided_items:
      "2인 음료 2잔 (아메리카노 or 시그니처 라떼)\n시즌 디저트 1종\n※ 동반 1인 가능",
    search_keywords_text:
      "성수동카페, 성수카페추천, 성수역카페, 스페셜티커피, 성수동맛집",
    mission:
      "1. 매장 외관 + 내부 인테리어 사진 각 2장 이상\n2. 음료 & 디저트 클로즈업 사진 3장 이상\n3. 맛, 분위기, 접근성 등 솔직한 후기 작성\n4. 네이버 지도 저장 인증 캡처 포함\n5. 위치 정보 및 영업시간 기재",
    required_qa:
      "Q1. 블로그 일평균 방문자 수는?\nQ2. 성수동 방문 가능한 요일/시간대는?",
    guidelines: null,
    required_keywords: ["성수동카페", "성수카페추천"],
    required_images_count: 7,
    min_text_length: 800,
    created_at: daysFromNow(-7),
    updated_at: daysFromNow(-5),
    points_amount: 0,
    store_name: "언더독 로스터스",
    store_address: "서울 성동구 연무장길 45, 1층",
    store_lat: 37.5445,
    store_lng: 127.0567,
    shipping_required: false,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 3. 올리브영 스킨케어 인스타 체험단 (active, seller, instagram) ──
  {
    id: "demo-camp-003",
    advertiser_id: "demo-advertiser-001",
    title: "올리브영 스킨케어 인스타 체험단",
    description:
      "라운드랩 독도 토너 & 세럼 세트를 체험하고 인스타그램 피드 포스팅을 작성해주세요. 실제 사용 후 피부 변화를 공유해주시면 됩니다.",
    campaign_type: "seller",
    required_channel: "instagram",
    category_name: "뷰티",
    region: null,
    compensation_type: "product_and_cash",
    compensation_value: "라운드랩 독도 토너+세럼 세트 + 원고료 3만원",
    cash_amount: 30000,
    product_name: "라운드랩 독도 토너+세럼 세트",
    product_value: 42000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 20,
    current_applicants: 18,
    apply_start: daysFromNow(-7),
    apply_end: daysFromNow(7),
    announce_date: daysFromNow(9),
    register_start: daysFromNow(9),
    register_end: daysFromNow(23),
    deadline_date: daysFromNow(25),
    recruitment_start: daysFromNow(-7),
    recruitment_end: daysFromNow(7),
    selection_date: daysFromNow(9),
    content_deadline: daysFromNow(23),
    publish_deadline: daysFromNow(25),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "active",
    is_featured: false,
    is_premium: true,
    view_count: 612,
    provided_items:
      "라운드랩 독도 토너 200ml 1개\n라운드랩 독도 세럼 40ml 1개\n파우치 포함",
    search_keywords_text:
      "라운드랩, 독도토너, 올리브영추천, 스킨케어루틴, 토너추천",
    mission:
      "1. 인스타그램 피드 게시물 1개 이상 (캐러셀 가능)\n2. 최소 7일 사용 후 피부 변화 비교 사진 포함\n3. 제품 텍스처, 향, 흡수력 등 상세 리뷰\n4. 해시태그: #라운드랩 #독도토너 #올리브영추천 필수\n5. 협찬 표시 (@brightcommerce 태그)",
    required_qa:
      "Q1. 피부 타입은? (건성/지성/복합성/민감성)\nQ2. 인스타그램 팔로워 수는?\nQ3. 뷰티 관련 피드 포스팅 경험이 있으신가요?",
    guidelines: null,
    required_keywords: ["라운드랩", "독도토너", "올리브영추천"],
    required_images_count: 4,
    min_text_length: 0,
    created_at: daysFromNow(-10),
    updated_at: daysFromNow(-7),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 4. 제주 호텔 숙박 릴스 체험단 (active, place, reels) ──
  {
    id: "demo-camp-004",
    advertiser_id: "demo-advertiser-001",
    title: "제주 호텔 숙박 릴스 체험단",
    description:
      "제주 서귀포시 중문에 위치한 '파라다이스 호텔 제주'에서 1박 숙박 후 인스타그램 릴스를 제작해주세요. 오션뷰 객실과 조식 뷔페가 제공됩니다.",
    campaign_type: "place",
    required_channel: "reels",
    category_name: "숙박",
    region: "제주",
    compensation_type: "product",
    compensation_value: "오션뷰 디럭스룸 1박 + 2인 조식 (350,000원 상당)",
    cash_amount: 0,
    product_name: "호텔 숙박권",
    product_value: 350000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 5,
    current_applicants: 5,
    apply_start: daysFromNow(-10),
    apply_end: daysFromNow(4),
    announce_date: daysFromNow(6),
    register_start: daysFromNow(6),
    register_end: daysFromNow(27),
    deadline_date: daysFromNow(30),
    recruitment_start: daysFromNow(-10),
    recruitment_end: daysFromNow(4),
    selection_date: daysFromNow(6),
    content_deadline: daysFromNow(27),
    publish_deadline: daysFromNow(30),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "active",
    is_featured: true,
    is_premium: true,
    view_count: 1023,
    provided_items:
      "오션뷰 디럭스룸 1박\n2인 조식 뷔페\n야외 인피니티풀 이용\n※ 주말 투숙 가능 (금/토 포함)",
    search_keywords_text:
      "제주호텔, 중문호텔, 제주숙소추천, 제주여행, 오션뷰호텔",
    mission:
      "1. 릴스 30~60초 분량 1개 제작\n2. 객실, 조식, 수영장 등 주요 시설 포함\n3. 위치 태그 + 호텔 공식 계정 태그\n4. 트렌디한 BGM 사용 권장\n5. 스토리 3컷 이상 업로드",
    required_qa:
      "Q1. 인스타그램 팔로워 수와 릴스 평균 조회수는?\nQ2. 여행/숙소 관련 콘텐츠 제작 경험이 있나요?\nQ3. 희망 투숙일 (2주 내 선택)",
    guidelines: null,
    required_keywords: ["제주호텔", "중문호텔"],
    required_images_count: 0,
    min_text_length: 0,
    created_at: daysFromNow(-14),
    updated_at: daysFromNow(-10),
    points_amount: 0,
    store_name: "파라다이스 호텔 제주",
    store_address: "제주특별자치도 서귀포시 중문관광로 72번길 100",
    store_lat: 33.2489,
    store_lng: 126.4103,
    shipping_required: false,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 5. 아이폰 케이스 틱톡 언박싱 (active, seller, tiktok) ──
  {
    id: "demo-camp-005",
    advertiser_id: "demo-advertiser-001",
    title: "아이폰 케이스 틱톡 언박싱",
    description:
      "MagSafe 대응 프리미엄 아이폰 16 케이스 3종을 받아 틱톡 언박싱 영상을 제작해주세요. 케이스 착용감과 디자인을 중심으로 리뷰해주시면 됩니다.",
    campaign_type: "seller",
    required_channel: "tiktok",
    category_name: "IT",
    region: null,
    compensation_type: "product",
    compensation_value: "프리미엄 아이폰 케이스 3종 세트 (89,000원 상당)",
    cash_amount: 0,
    product_name: "아이폰 16 MagSafe 케이스 3종",
    product_value: 89000,
    purchase_link: "https://smartstore.naver.com/casemania-official",
    purchase_price: 89000,
    max_applicants: 12,
    current_applicants: 8,
    apply_start: daysFromNow(-2),
    apply_end: daysFromNow(12),
    announce_date: daysFromNow(14),
    register_start: daysFromNow(14),
    register_end: daysFromNow(24),
    deadline_date: daysFromNow(26),
    recruitment_start: daysFromNow(-2),
    recruitment_end: daysFromNow(12),
    selection_date: daysFromNow(14),
    content_deadline: daysFromNow(24),
    publish_deadline: daysFromNow(26),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "active",
    is_featured: false,
    is_premium: false,
    view_count: 256,
    provided_items:
      "아이폰 16 MagSafe 케이스 3종 (클리어/매트블랙/네이비)\n개별 포장 박스 포함",
    search_keywords_text:
      "아이폰케이스, 아이폰16케이스, MagSafe케이스, 케이스추천, 폰케이스",
    mission:
      "1. 틱톡 언박싱 영상 30~60초\n2. 3종 케이스 비교 착용 장면 포함\n3. MagSafe 부착 시연\n4. 해시태그 #아이폰케이스 #아이폰16 #언박싱 필수\n5. 프로필 링크에 구매링크 삽입",
    required_qa:
      "Q1. 틱톡 팔로워 수는?\nQ2. 현재 사용 중인 아이폰 모델은?\nQ3. IT/가젯 관련 콘텐츠 제작 경험이 있나요?",
    guidelines: null,
    required_keywords: ["아이폰16케이스", "MagSafe케이스"],
    required_images_count: 0,
    min_text_length: 0,
    created_at: daysFromNow(-4),
    updated_at: daysFromNow(-2),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 6. 유기농 강아지 간식 쇼츠 체험단 (in_progress, seller, shorts) ──
  {
    id: "demo-camp-006",
    advertiser_id: "demo-advertiser-001",
    title: "유기농 강아지 간식 쇼츠 체험단",
    description:
      "USDA 인증 유기농 원료로 만든 '펫프렌즈 내추럴 트릿' 3종을 받아 유튜브 쇼츠를 촬영해주세요. 반려견이 간식을 먹는 귀여운 모습을 담아주시면 됩니다.",
    campaign_type: "seller",
    required_channel: "shorts",
    category_name: "반려동물",
    region: null,
    compensation_type: "product",
    compensation_value: "유기농 강아지 간식 3종 세트 (45,000원 상당)",
    cash_amount: 0,
    product_name: "펫프렌즈 내추럴 트릿 3종",
    product_value: 45000,
    purchase_link: "https://smartstore.naver.com/petfriends-official",
    purchase_price: 45000,
    max_applicants: 10,
    current_applicants: 10,
    apply_start: daysFromNow(-21),
    apply_end: daysFromNow(-11),
    announce_date: daysFromNow(-9),
    register_start: daysFromNow(-9),
    register_end: daysFromNow(1),
    deadline_date: daysFromNow(3),
    recruitment_start: daysFromNow(-21),
    recruitment_end: daysFromNow(-11),
    selection_date: daysFromNow(-9),
    content_deadline: daysFromNow(1),
    publish_deadline: daysFromNow(3),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "in_progress",
    is_featured: false,
    is_premium: false,
    view_count: 389,
    provided_items:
      "펫프렌즈 내추럴 트릿 - 닭가슴살 1팩\n펫프렌즈 내추럴 트릿 - 연어 1팩\n펫프렌즈 내추럴 트릿 - 고구마 1팩",
    search_keywords_text:
      "강아지간식, 유기농강아지간식, 강아지간식추천, 펫프렌즈, 수제간식",
    mission:
      "1. 유튜브 쇼츠 30~60초 촬영\n2. 반려견이 간식 먹는 ASMR or 먹방 장면 포함\n3. 원료 성분표 클로즈업\n4. 쇼츠 설명란에 구매링크 삽입\n5. #강아지간식 #유기농간식 해시태그",
    required_qa:
      "Q1. 반려견 견종과 나이는?\nQ2. 유튜브 채널명과 구독자 수는?\nQ3. 알러지 유발 원료가 있다면 알려주세요",
    guidelines: null,
    required_keywords: ["유기농강아지간식", "강아지간식추천"],
    required_images_count: 0,
    min_text_length: 0,
    created_at: daysFromNow(-25),
    updated_at: daysFromNow(-9),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 7. 다이어트 보조제 구매평+블로그 (in_progress, seller, purchase_blog) ──
  {
    id: "demo-camp-007",
    advertiser_id: "demo-advertiser-001",
    title: "다이어트 보조제 구매평+블로그",
    description:
      "CLA 다이어트 보조제를 구매 후 네이버 구매평과 블로그 포스팅을 동시에 작성해주세요. 2주 섭취 후 변화를 기록해주시면 됩니다.",
    campaign_type: "seller",
    required_channel: "purchase_blog",
    category_name: "식품",
    region: null,
    compensation_type: "product_and_cash",
    compensation_value: "CLA 다이어트 보조제 2개월분 + 원고료 2만원",
    cash_amount: 20000,
    product_name: "그린핏 CLA 다이어트",
    product_value: 58000,
    purchase_link: "https://smartstore.naver.com/greenfit-official",
    purchase_price: 29000,
    max_applicants: 15,
    current_applicants: 15,
    apply_start: daysFromNow(-28),
    apply_end: daysFromNow(-18),
    announce_date: daysFromNow(-16),
    register_start: daysFromNow(-16),
    register_end: daysFromNow(-2),
    deadline_date: daysFromNow(0),
    recruitment_start: daysFromNow(-28),
    recruitment_end: daysFromNow(-18),
    selection_date: daysFromNow(-16),
    content_deadline: daysFromNow(-2),
    publish_deadline: daysFromNow(0),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "in_progress",
    is_featured: false,
    is_premium: false,
    view_count: 445,
    provided_items:
      "그린핏 CLA 다이어트 2개월분 (60정 x 2통)\n식단 관리 가이드북 PDF",
    search_keywords_text:
      "다이어트보조제, CLA다이어트, 다이어트식품추천, 체지방감소",
    mission:
      "1. 네이버 스마트스토어 구매평 작성 (사진 포함)\n2. 블로그 포스팅 1,000자 이상\n3. 2주 섭취 전후 경험 공유\n4. 성분 분석 및 섭취 방법 안내 포함\n5. 건강기능식품 관련 주의사항 문구 필수",
    required_qa:
      "Q1. 건강 보조제 리뷰 경험이 있으신가요?\nQ2. 블로그 일평균 방문자 수는?\nQ3. 식품 알레르기가 있으신가요?",
    guidelines: null,
    required_keywords: ["다이어트보조제", "CLA다이어트"],
    required_images_count: 5,
    min_text_length: 1000,
    created_at: daysFromNow(-30),
    updated_at: daysFromNow(-16),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 8. 홍대 네일아트 블로그 체험단 (completed, place, blog_reporter) ──
  {
    id: "demo-camp-008",
    advertiser_id: "demo-advertiser-001",
    title: "홍대 네일아트 블로그 체험단",
    description:
      "홍대입구역 근처 프리미엄 네일 샵 '네일가든'을 방문하여 젤네일 시술을 받고 블로그 기자단 형식의 상세 리뷰를 작성해주세요.",
    campaign_type: "place",
    required_channel: "blog_reporter",
    category_name: "뷰티",
    region: "서울",
    compensation_type: "product",
    compensation_value: "젤네일 아트 시술 무료 (7만원 상당)",
    cash_amount: 0,
    product_name: "젤네일 아트",
    product_value: 70000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 8,
    current_applicants: 8,
    apply_start: daysFromNow(-35),
    apply_end: daysFromNow(-25),
    announce_date: daysFromNow(-23),
    register_start: daysFromNow(-23),
    register_end: daysFromNow(-9),
    deadline_date: daysFromNow(-7),
    recruitment_start: daysFromNow(-35),
    recruitment_end: daysFromNow(-25),
    selection_date: daysFromNow(-23),
    content_deadline: daysFromNow(-9),
    publish_deadline: daysFromNow(-7),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "completed",
    is_featured: false,
    is_premium: false,
    view_count: 278,
    provided_items:
      "젤네일 아트 시술 1회 (디자인 자유 선택)\n핸드크림 샘플 1개",
    search_keywords_text:
      "홍대네일, 홍대네일아트, 젤네일추천, 홍대네일샵, 네일아트추천",
    mission:
      "1. 시술 과정 사진 3장 이상 (시술 전/중/후)\n2. 완성된 네일 클로즈업 사진 5장 이상\n3. 매장 분위기, 접근성, 가격대 정보 포함\n4. 솔직한 시술 만족도 평가\n5. 네이버 지도 리뷰 동시 등록",
    required_qa:
      "Q1. 네일아트 시술 경험이 있으신가요?\nQ2. 선호하는 네일 디자인 스타일은?",
    guidelines: null,
    required_keywords: ["홍대네일아트", "젤네일추천"],
    required_images_count: 8,
    min_text_length: 800,
    created_at: daysFromNow(-38),
    updated_at: daysFromNow(-7),
    points_amount: 0,
    store_name: "네일가든 홍대점",
    store_address: "서울 마포구 와우산로 94, 3층",
    store_lat: 37.5563,
    store_lng: 126.9236,
    shipping_required: false,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 9. 캠핑 용품 네이버 인플루언서 (completed, seller, naver_influencer) ──
  {
    id: "demo-camp-009",
    advertiser_id: "demo-advertiser-001",
    title: "캠핑 용품 네이버 인플루언서",
    description:
      "2026년 신제품 경량 캠핑 체어 '에어체어 프로'를 체험하고 네이버 인플루언서 홈에 상세 리뷰를 포스팅해주세요.",
    campaign_type: "seller",
    required_channel: "naver_influencer",
    category_name: "생활",
    region: null,
    compensation_type: "product_and_cash",
    compensation_value: "에어체어 프로 1개 + 원고료 5만원",
    cash_amount: 50000,
    product_name: "에어체어 프로",
    product_value: 129000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 5,
    current_applicants: 5,
    apply_start: daysFromNow(-42),
    apply_end: daysFromNow(-32),
    announce_date: daysFromNow(-30),
    register_start: daysFromNow(-30),
    register_end: daysFromNow(-16),
    deadline_date: daysFromNow(-14),
    recruitment_start: daysFromNow(-42),
    recruitment_end: daysFromNow(-32),
    selection_date: daysFromNow(-30),
    content_deadline: daysFromNow(-16),
    publish_deadline: daysFromNow(-14),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "completed",
    is_featured: false,
    is_premium: true,
    view_count: 534,
    provided_items:
      "에어체어 프로 1개 (카키/블랙 선택)\n전용 수납 파우치 포함\n현금 원고료 50,000원 (세후 지급)",
    search_keywords_text:
      "캠핑체어, 경량캠핑의자, 캠핑용품추천, 에어체어, 캠핑의자추천",
    mission:
      "1. 네이버 인플루언서 홈에 리뷰 포스팅 (1,500자 이상)\n2. 실제 캠핑장에서 사용 사진 5장 이상\n3. 무게, 조립 편의성, 내구성 등 항목별 평가\n4. 타 브랜드 비교 분석 포함 시 우대\n5. 키워드 챌린지 참여",
    required_qa:
      "Q1. 네이버 인플루언서 팬 수는?\nQ2. 캠핑 관련 포스팅 경험이 있으신가요?\nQ3. 캠핑 횟수 (월 기준)는?",
    guidelines: null,
    required_keywords: ["캠핑체어추천", "경량캠핑의자"],
    required_images_count: 5,
    min_text_length: 1500,
    created_at: daysFromNow(-45),
    updated_at: daysFromNow(-14),
    points_amount: 0,
    store_name: null,
    store_address: null,
    store_lat: null,
    store_lng: null,
    shipping_required: true,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },

  // ── 10. 부산 횟집 방문 블로그기자단 (draft, place, blog) ──
  {
    id: "demo-camp-010",
    advertiser_id: "demo-advertiser-001",
    title: "부산 횟집 방문 블로그기자단",
    description:
      "부산 해운대 '바다원 활어회' 매장을 방문하여 모듬회 코스를 체험하고 네이버 블로그에 상세 리뷰를 작성해주세요. 기자단 형식으로 운영됩니다.",
    campaign_type: "place",
    required_channel: "blog",
    category_name: "맛집",
    region: "부산",
    compensation_type: "product",
    compensation_value: "모듬회 2인 코스 무료 제공 (12만원 상당)",
    cash_amount: 0,
    product_name: "모듬회 2인 코스",
    product_value: 120000,
    purchase_link: null,
    purchase_price: null,
    max_applicants: 6,
    current_applicants: 0,
    apply_start: daysFromNow(5),
    apply_end: daysFromNow(19),
    announce_date: daysFromNow(21),
    register_start: daysFromNow(21),
    register_end: daysFromNow(35),
    deadline_date: daysFromNow(37),
    recruitment_start: daysFromNow(5),
    recruitment_end: daysFromNow(19),
    selection_date: daysFromNow(21),
    content_deadline: daysFromNow(35),
    publish_deadline: daysFromNow(37),
    thumbnail_url: null,
    images: [],
    detail_images: [],
    status: "draft",
    is_featured: false,
    is_premium: false,
    view_count: 0,
    provided_items:
      "모듬회 2인 코스 (광어, 우럭, 도미, 참치 포함)\n매운탕 1인분\n소주 1병",
    search_keywords_text:
      "부산횟집, 해운대맛집, 해운대횟집, 부산회추천, 부산맛집",
    mission:
      "1. 매장 외관/내부 사진 각 2장\n2. 회 플레이팅 & 매운탕 클로즈업 사진 5장 이상\n3. 맛, 신선도, 서비스, 가성비 등 항목별 평가\n4. 네이버 지도 영수증 리뷰 동시 등록\n5. 위치/영업시간/주차 정보 필수 기재",
    required_qa:
      "Q1. 부산 거주자 또는 방문 예정이신가요?\nQ2. 맛집 블로그 운영 경험이 있으신가요?\nQ3. 블로그 일평균 방문자 수는?",
    guidelines: null,
    required_keywords: ["해운대횟집", "부산맛집"],
    required_images_count: 9,
    min_text_length: 1000,
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
    points_amount: 0,
    store_name: "바다원 활어회",
    store_address: "부산광역시 해운대구 해운대해변로 298번길 12",
    store_lat: 35.1587,
    store_lng: 129.1604,
    shipping_required: false,
    reference_urls: null,
    category_id: null,
    advertiser: advertiserTag,
  },
];

// ---------------------------------------------------------------------------
// Demo applications (influencer view -- the demo influencer's applications)
// ---------------------------------------------------------------------------
export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "demo-app-001",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-influencer-001",
    message:
      "IT 기기 전문 블로거입니다. 현재 에어팟 프로 사용 중이며 갤럭시 버즈와의 비교 리뷰도 가능합니다.",
    social_account_id: null,
    status: "selected",
    selected_at: daysFromNow(-1),
    rejected_reason: null,
    match_score: null,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-1),
    campaign: DEMO_CAMPAIGNS[0],
  },
  {
    id: "demo-app-002",
    campaign_id: "demo-camp-002",
    influencer_id: "demo-influencer-001",
    message:
      "성수동 거주자입니다. 카페 리뷰 전문 블로거로 일평균 방문자 2,800명입니다.",
    social_account_id: null,
    status: "pending",
    selected_at: null,
    rejected_reason: null,
    match_score: null,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-4),
    updated_at: daysFromNow(-4),
    campaign: DEMO_CAMPAIGNS[1],
  },
  {
    id: "demo-app-003",
    campaign_id: "demo-camp-003",
    influencer_id: "demo-influencer-001",
    message:
      "뷰티 인스타그램 팔로워 1.5만명입니다. 스킨케어 제품 리뷰를 주로 합니다.",
    social_account_id: null,
    status: "selected",
    selected_at: daysFromNow(-2),
    rejected_reason: null,
    match_score: null,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-6),
    updated_at: daysFromNow(-2),
    campaign: DEMO_CAMPAIGNS[2],
  },
  {
    id: "demo-app-004",
    campaign_id: "demo-camp-008",
    influencer_id: "demo-influencer-001",
    message: "네일아트 블로거입니다. 홍대 지역 맛집/뷰티 전문 리뷰어입니다.",
    social_account_id: null,
    status: "rejected",
    selected_at: null,
    rejected_reason: "지원자가 많아 이번에는 선정이 어렵습니다. 다음 기회에 꼭 함께하고 싶습니다.",
    match_score: null,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-33),
    updated_at: daysFromNow(-23),
    campaign: DEMO_CAMPAIGNS[7],
  },
  {
    id: "demo-app-005",
    campaign_id: "demo-camp-006",
    influencer_id: "demo-influencer-001",
    message:
      "골든리트리버 키우고 있어요! 반려동물 쇼츠 채널 운영 중이고 구독자 3,200명입니다.",
    social_account_id: null,
    status: "selected",
    selected_at: daysFromNow(-9),
    rejected_reason: null,
    match_score: null,
    product_shipped: true,
    product_shipped_at: daysFromNow(-7),
    tracking_number: "CJ1234567890",
    visited_at: null,
    created_at: daysFromNow(-18),
    updated_at: daysFromNow(-7),
    campaign: DEMO_CAMPAIGNS[5],
  },
];

// ---------------------------------------------------------------------------
// Demo applicants (advertiser campaign detail view -- who applied to a campaign)
// ---------------------------------------------------------------------------
export const DEMO_APPLICANTS: Application[] = [
  {
    id: "demo-applicant-001",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-001",
    message:
      "IT 기기 전문 블로거입니다. 삼성 제품 리뷰 경험 다수 보유하고 있습니다.",
    social_account_id: null,
    status: "selected",
    selected_at: daysFromNow(-1),
    rejected_reason: null,
    match_score: 94,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-1),
    influencer: {
      id: "demo-inf-001",
      bio: "IT 기기와 가젯을 사랑하는 테크 블로거",
      gender: "male",
      birth_date: "1993-05-12",
      region: "서울",
      address: null,
      zipcode: null,
      tier: "gold",
      tier_updated_at: daysFromNow(-60),
      total_campaigns_completed: 23,
      total_points_earned: 0,
      average_rating: 4.9,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-180),
      profile: {
        id: "demo-inf-001",
        role: "influencer",
        display_name: "테크리뷰어 민수",
        email: "minsu@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s1",
          influencer_id: "demo-inf-001",
          platform: "naver_blog",
          account_url: "https://blog.naver.com/techminsu",
          account_name: "테크민수",
          follower_count: 14200,
          average_views: 3800,
          average_likes: 0,
          is_verified: true,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
  {
    id: "demo-applicant-002",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-002",
    message:
      "직장인 가젯 리뷰어입니다. 매주 1개 이상의 IT 제품 리뷰를 포스팅합니다.",
    social_account_id: null,
    status: "selected",
    selected_at: daysFromNow(-1),
    rejected_reason: null,
    match_score: 89,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-1),
    influencer: {
      id: "demo-inf-002",
      bio: "회사원이자 가젯 덕후. 솔직한 리뷰가 철학입니다",
      gender: "male",
      birth_date: "1990-11-08",
      region: "경기",
      address: null,
      zipcode: null,
      tier: "silver",
      tier_updated_at: daysFromNow(-90),
      total_campaigns_completed: 11,
      total_points_earned: 0,
      average_rating: 4.6,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-120),
      profile: {
        id: "demo-inf-002",
        role: "influencer",
        display_name: "가젯러 현우",
        email: "hyunwoo@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s2",
          influencer_id: "demo-inf-002",
          platform: "naver_blog",
          account_url: "https://blog.naver.com/gadget-hw",
          account_name: "가젯현우",
          follower_count: 9800,
          average_views: 2400,
          average_likes: 0,
          is_verified: false,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
  {
    id: "demo-applicant-003",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-003",
    message:
      "일상+IT 블로그 운영 중입니다. 이어폰 리뷰가 인기 콘텐츠예요.",
    social_account_id: null,
    status: "pending",
    selected_at: null,
    rejected_reason: null,
    match_score: 72,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-2),
    influencer: {
      id: "demo-inf-003",
      bio: "육아하며 블로그 쓰는 워킹맘",
      gender: "female",
      birth_date: "1991-03-22",
      region: "서울",
      address: null,
      zipcode: null,
      tier: "standard",
      tier_updated_at: daysFromNow(-30),
      total_campaigns_completed: 4,
      total_points_earned: 0,
      average_rating: 4.2,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-90),
      profile: {
        id: "demo-inf-003",
        role: "influencer",
        display_name: "일상로그 하은",
        email: "haeun@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s3",
          influencer_id: "demo-inf-003",
          platform: "naver_blog",
          account_url: "https://blog.naver.com/haeun-daily",
          account_name: "하은의 일상로그",
          follower_count: 4100,
          average_views: 1200,
          average_likes: 0,
          is_verified: false,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
  {
    id: "demo-applicant-004",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-004",
    message:
      "유튜브에서 음향 기기 리뷰 채널을 운영하고 있습니다. 블로그 교차 포스팅 가능합니다.",
    social_account_id: null,
    status: "pending",
    selected_at: null,
    rejected_reason: null,
    match_score: 78,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-2),
    influencer: {
      id: "demo-inf-004",
      bio: "음향 기기 전문 리뷰어 / 오디오 엔지니어 출신",
      gender: "male",
      birth_date: "1988-07-15",
      region: "서울",
      address: null,
      zipcode: null,
      tier: "gold",
      tier_updated_at: daysFromNow(-45),
      total_campaigns_completed: 19,
      total_points_earned: 0,
      average_rating: 4.8,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-200),
      profile: {
        id: "demo-inf-004",
        role: "influencer",
        display_name: "오디오매니아 재현",
        email: "jaehyun@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s4",
          influencer_id: "demo-inf-004",
          platform: "naver_blog",
          account_url: "https://blog.naver.com/audiojh",
          account_name: "오디오재현",
          follower_count: 11500,
          average_views: 3200,
          average_likes: 0,
          is_verified: true,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
  {
    id: "demo-applicant-005",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-005",
    message:
      "패션/라이프스타일 인스타그래머입니다. IT 가젯도 스타일리시하게 소개합니다.",
    social_account_id: null,
    status: "rejected",
    selected_at: null,
    rejected_reason: "블로그 채널 캠페인이라 인스타그램 위주의 활동과 맞지 않습니다.",
    match_score: 45,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-1),
    influencer: {
      id: "demo-inf-005",
      bio: "패션과 라이프스타일을 기록하는 인스타그래머",
      gender: "female",
      birth_date: "1995-09-30",
      region: "서울",
      address: null,
      zipcode: null,
      tier: "silver",
      tier_updated_at: daysFromNow(-50),
      total_campaigns_completed: 9,
      total_points_earned: 0,
      average_rating: 4.4,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-150),
      profile: {
        id: "demo-inf-005",
        role: "influencer",
        display_name: "유니크 소정",
        email: "sojeong@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s5",
          influencer_id: "demo-inf-005",
          platform: "instagram",
          account_url: "https://instagram.com/unique_sojeong",
          account_name: "@unique_sojeong",
          follower_count: 22400,
          average_views: 0,
          average_likes: 850,
          is_verified: false,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
  {
    id: "demo-applicant-006",
    campaign_id: "demo-camp-001",
    influencer_id: "demo-inf-006",
    message:
      "대학생 IT 블로거입니다. 가성비 위주 리뷰를 주로 합니다. 사진 퀄리티 자신 있습니다.",
    social_account_id: null,
    status: "pending",
    selected_at: null,
    rejected_reason: null,
    match_score: 68,
    product_shipped: false,
    product_shipped_at: null,
    tracking_number: null,
    visited_at: null,
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
    influencer: {
      id: "demo-inf-006",
      bio: "컴퓨터공학과 재학 중 / 가성비 IT 리뷰어",
      gender: "male",
      birth_date: "2001-02-14",
      region: "대전",
      address: null,
      zipcode: null,
      tier: "standard",
      tier_updated_at: daysFromNow(-20),
      total_campaigns_completed: 2,
      total_points_earned: 0,
      average_rating: 4.0,
      warning_count: 0,
      is_blacklisted: false,
      created_at: daysFromNow(-60),
      profile: {
        id: "demo-inf-006",
        role: "influencer",
        display_name: "가성비왕 도현",
        email: "dohyun@demo.com",
        phone: null,
        avatar_url: null,
        is_active: true,
        created_at: "",
        updated_at: "",
      },
      social_accounts: [
        {
          id: "s6",
          influencer_id: "demo-inf-006",
          platform: "naver_blog",
          account_url: "https://blog.naver.com/budget-dh",
          account_name: "가성비도현",
          follower_count: 2800,
          average_views: 900,
          average_likes: 0,
          is_verified: false,
          connected_at: "",
          stats_updated_at: null,
        },
      ],
    },
  },
];

// ---------------------------------------------------------------------------
// Helper: check if currently in demo mode (client-side)
// ---------------------------------------------------------------------------
export function isDemoMode(): false | "advertiser" | "influencer" {
  if (typeof document === "undefined") return false;
  const match = document.cookie.match(/(?:^|; )adlumin_demo=([^;]*)/);
  if (!match) return false;
  const value = match[1];
  if (value === "advertiser" || value === "influencer") return value;
  return false;
}

// ---------------------------------------------------------------------------
// Helper: clear demo mode
// ---------------------------------------------------------------------------
export function clearDemoMode() {
  document.cookie = "adlumin_demo=; path=/; max-age=0";
}

// ---------------------------------------------------------------------------
// Helper: toggle demo mode to a different role (calls API, returns a promise)
// ---------------------------------------------------------------------------
export async function toggleDemoMode(
  role: "advertiser" | "influencer",
): Promise<boolean> {
  try {
    const res = await fetch("/api/demo-login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ role }),
    });
    return res.ok;
  } catch {
    return false;
  }
}
